#https://roadrunner.dev/docs/intro-config
version: "3"
rpc:
  listen: tcp://127.0.0.1:6001
server:
  command: "php bin/roadrunner.php -dopcache.jit=tracing -dopcache.jit_buffer_size=100M"
  user: "www-data"
  env:
    - OTEL_SERVICE_NAME: php
    - OTEL_TRACES_EXPORTER: otlp
    - OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
    - OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.phpug.hh
    - OTEL_PHP_TRACES_PROCESSOR: simple
  relay: pipes
logs:
  mode: production
  level: info
  encoding: json
otel:
  resource:
    service_name: roadrunner-demo
    service_version: 1.0.0
  insecure: true
  compress: false
  client: http
  exporter: otlp
  endpoint: otel-collector:4318
http:
  fcgi:
    address: tcp://0.0.0.0:9000
  pool:
    num_workers: 4
    max_jobs: 1000
    allocate_timeout: 30s
    reset_timeout: 30s
    destroy_timeout: 30s
    supervisor:
      watch_tick: 1s
      ttl: 3600s
      idle_ttl: 120s
      max_worker_memory: 1024
      exec_ttl: 60s
  middleware: [gzip, otel]
