---
application:
  name: roadrunner
  version: 1.0.0
system:
  host: dev01.test.int.phphug.hh
  stage: dev
database:
  host: mariadb
  username: root
  password: phpughh
  database: phpughh
  cachePath: /var/www/webapp/tmp/cache/doctrine
  proxyPath: /var/www/webapp/tmp/proxies
  entityPaths:
    - /var/www/webapp/src/Infrastructure/Database/Users
  debug: true
  cache: false
framework:
  di:
    cachePath: /var/www/webapp/tmp/cache/php-di
    debug: false
    cache: false
    compile: false
    proxies: false
  log:
    logLevel: debug
    logPath: /var/www/webapp/tmp/log
#    logType: local
    logType: graylog
    debug: false
  router:
    cachePath: /var/www/webapp/tmp/cache/fast-route
    debug: false
    cache: false
  templating:
    baseVars:
      page_title: Roadrunner
      copyright_year: "2023"
    cachePath: /var/www/webapp/tmp/cache/twig
    cache: false
    templatePath: /var/www/webapp/templates
...
