services:
  dev-cli:
    build:
      context: build/dev-cli
      args:
        codeception_version: ${CODECEPTION_VERSION}
        codeception_asserts_version: ${CODECEPTION_ASSERTS_VERSION}
        mariadb_root_password: ${MARIADB_ROOT_PASSWORD}
        php_version: ${PHP_VERSION}
      tags:
        - phpughh/roadrunner/php:${PHP_VERSION_MAJOR}.${PHP_VERSION_MINOR}-cli
        - phpughh/roadrunner/php:${PHP_VERSION_MAJOR}-cli
        - phpughh/roadrunner/php:latest-cli
    image: phpughh/roadrunner/php:${PHP_VERSION}-cli

  grafana:
    build:
      context: build/grafana
      args:
        grafana_version: ${GRAFANA_VERSION}
      tags:
        - phpughh/roadrunner/grafana:${GRAFANA_VERSION_MAJOR}.${GRAFANA_VERSION_MINOR}
        - phpughh/roadrunner/grafana:${GRAFANA_VERSION_MAJOR}
        - phpughh/roadrunner/grafana:latest
    image: phpughh/roadrunner/grafana:${GRAFANA_VERSION}

  filebeat:
    build:
      context: build/filebeat
      args:
        filebeat_version: ${FILEBEAT_VERSION}
      tags:
        - phpughh/roadrunner/filebeat:${FILEBEAT_VERSION_MAJOR}.${FILEBEAT_VERSION_MINOR}
        - phpughh/roadrunner/filebeat:${FILEBEAT_VERSION_MAJOR}
        - phpughh/roadrunner/filebeat:latest
    image: phpughh/roadrunner/filebeat:${FILEBEAT_VERSION}

  graylog:
    build:
      context: build/graylog
      args:
        graylog_version: ${GRAYLOG_VERSION}
      tags:
        - phpughh/roadrunner/graylog:${GRAYLOG_VERSION_MAJOR}.${GRAYLOG_VERSION_MINOR}.${GRAYLOG_VERSION_BUGFIX}
        - phpughh/roadrunner/graylog:${GRAYLOG_VERSION_MAJOR}.${GRAYLOG_VERSION_MINOR}
        - phpughh/roadrunner/graylog:${GRAYLOG_VERSION_MAJOR}
        - phpughh/roadrunner/graylog:latest
    image: phpughh/roadrunner/graylog:${GRAYLOG_VERSION}

  graylog-sidecar:
    build:
      context: build/graylog-sidecar
      args:
        graylog_sidecar_version: ${GRAYLOG_SIDECAR_VERSION}
        graylog_sidecar_version_patch: ${GRAYLOG_SIDECAR_VERSION_PATCH}
        ubuntu_version: ${UBUNTU_VERSION_GRAYLOG_SIDECAR}
      tags:
        - phpughh/roadrunner/graylog-sidecar:${GRAYLOG_SIDECAR_VERSION_MAJOR}.${GRAYLOG_SIDECAR_VERSION_MINOR}.${GRAYLOG_SIDECAR_VERSION_BUGFIX}
        - phpughh/roadrunner/graylog-sidecar:${GRAYLOG_SIDECAR_VERSION_MAJOR}.${GRAYLOG_SIDECAR_VERSION_MINOR}
        - phpughh/roadrunner/graylog-sidecar:${GRAYLOG_SIDECAR_VERSION_MAJOR}
        - phpughh/roadrunner/graylog-sidecar:latest
    image: phpughh/roadrunner/graylog-sidecar:${GRAYLOG_SIDECAR_VERSION_FULL}

  mariadb:
    build:
      context: build/mariadb
      args:
        mariadb_version: ${MARIADB_VERSION}
      tags:
        - phpughh/roadrunner/mariadb:${MARIADB_VERSION_MAJOR}.${MARIADB_VERSION_MINOR}
        - phpughh/roadrunner/mariadb:${MARIADB_VERSION_MAJOR}
        - phpughh/roadrunner/mariadb:latest
    image: phpughh/roadrunner/mariadb:${MARIADB_VERSION}

  mongo:
    build:
      context: build/mongo
      args:
        mongo_version: ${MONGO_VERSION}
      tags:
        - phpughh/roadrunner/mongo:${MONGO_VERSION_MAJOR}.${MONGO_VERSION_MINOR}
        - phpughh/roadrunner/mongo:${MONGO_VERSION_MAJOR}
        - phpughh/roadrunner/mongo:latest
    image: phpughh/roadrunner/mongo:${MONGO_VERSION}

  nginx-base:
    build:
      context: build/nginx-base
      args:
        nginx_version: ${NGINX_VERSION}
      tags:
        - phpughh/roadrunner/nginx:${NGINX_VERSION_MAJOR}.${NGINX_VERSION_MINOR}-base
        - phpughh/roadrunner/nginx:${NGINX_VERSION_MAJOR}-base
        - phpughh/roadrunner/nginx:latest-base
    image: phpughh/roadrunner/nginx:${NGINX_VERSION}-base

  nginx:
    build:
      context: build/nginx
      args:
        nginx_version: ${NGINX_VERSION}
      tags:
        - phpughh/roadrunner/nginx:${NGINX_VERSION_MAJOR}.${NGINX_VERSION_MINOR}
        - phpughh/roadrunner/nginx:${NGINX_VERSION_MAJOR}
        - phpughh/roadrunner/nginx:latest
    image: phpughh/roadrunner/nginx:${NGINX_VERSION}

  opensearch:
    build:
      context: build/opensearch
      args:
        opensearch_version: ${OPENSEARCH_VERSION}
      tags:
        - phpughh/roadrunner/opensearch:${OPENSEARCH_VERSION_MAJOR}.${OPENSEARCH_VERSION_MINOR}.${OPENSEARCH_VERSION_BUGFIX}
        - phpughh/roadrunner/opensearch:${OPENSEARCH_VERSION_MAJOR}.${OPENSEARCH_VERSION_MINOR}
        - phpughh/roadrunner/opensearch:${OPENSEARCH_VERSION_MAJOR}
        - phpughh/roadrunner/opensearch:latest
    image: phpughh/roadrunner/opensearch:${OPENSEARCH_VERSION}

  otel-collector:
    build:
      context: build/otel-collector
      args:
        otel_collector_version: ${OTEL_COLLECTOR_VERSION}
      tags:
        - phpughh/roadrunner/otel-collector:${OTEL_COLLECTOR_VERSION_MAJOR}.${OTEL_COLLECTOR_VERSION_MINOR}
        - phpughh/roadrunner/otel-collector:${OTEL_COLLECTOR_VERSION_MAJOR}
        - phpughh/roadrunner/otel-collector:latest
    image: phpughh/roadrunner/otel-collector:${OTEL_COLLECTOR_VERSION}

  php:
    build:
      context: build/php-fpm
      args:
        php_version: ${PHP_VERSION}
      tags:
        - phpughh/roadrunner/php:${PHP_VERSION_MAJOR}.${PHP_VERSION_MINOR}-fpm
        - phpughh/roadrunner/php:${PHP_VERSION_MAJOR}-fpm
        - phpughh/roadrunner/php:latest-fpm
    image: phpughh/roadrunner/php:${PHP_VERSION}-fpm

  php-dev:
    build:
      context: build/php-fpm-dev
      args:
        php_version: ${PHP_VERSION}
      tags:
        - phpughh/roadrunner/php:${PHP_VERSION_MAJOR}.${PHP_VERSION_MINOR}-fpm-dev
        - phpughh/roadrunner/php:${PHP_VERSION_MAJOR}-fpm-dev
        - phpughh/roadrunner/php:latest-fpm-dev
    image: phpughh/roadrunner/php:${PHP_VERSION}-fpm-dev

  portainer:
    build:
      context: build/portainer
      args:
        portainer_version: ${PORTAINER_VERSION}
      tags:
        - phpughh/roadrunner/portainer:${PORTAINER_VERSION_MAJOR}.${PORTAINER_VERSION_MINOR}
        - phpughh/roadrunner/portainer:${PORTAINER_VERSION_MAJOR}
        - phpughh/roadrunner/portainer:latest
    image: phpughh/roadrunner/portainer:${PORTAINER_VERSION}

  prometheus:
    build:
      context: build/prometheus
      args:
        prometheus_version: ${PROMETHEUS_VERSION}
      tags:
        - phpughh/roadrunner/prometheus:${PROMETHEUS_VERSION_MAJOR}.${PROMETHEUS_VERSION_MINOR}
        - phpughh/roadrunner/prometheus:${PROMETHEUS_VERSION_MAJOR}
        - phpughh/roadrunner/prometheus:latest
    image: phpughh/roadrunner/prometheus:${PROMETHEUS_VERSION}

  roadrunner:
    build:
      context: build/php-rr
      args:
        php_version: ${PHP_VERSION}
        roadrunner_version: ${ROADRUNNER_VERSION}
      tags:
        - phpughh/roadrunner/roadrunner:${PHP_VERSION_MAJOR}.${PHP_VERSION_MINOR}-rr
        - phpughh/roadrunner/roadrunner:${PHP_VERSION_MAJOR}-rr
        - phpughh/roadrunner/roadrunner:latest-rr
    image: phpughh/roadrunner/php:${PHP_VERSION}-rr

  roadrunner-dev:
    build:
      context: build/php-rr-dev
      args:
        php_version: ${PHP_VERSION}
      tags:
        - phpughh/roadrunner/roadrunner:${PHP_VERSION_MAJOR}.${PHP_VERSION_MINOR}-rr-dev
        - phpughh/roadrunner/roadrunner:${PHP_VERSION_MAJOR}-rr-dev
        - phpughh/roadrunner/roadrunner:latest-rr-dev
    image: phpughh/roadrunner/php:${PHP_VERSION}-rr-dev

  traefik:
    build:
      context: build/traefik
      args:
        traefik_version: ${TRAEFIK_VERSION}
      tags:
        - phpughh/roadrunner/traefik:${TRAEFIK_VERSION_MAJOR}.${TRAEFIK_VERSION_MINOR}
        - phpughh/roadrunner/traefik:${TRAEFIK_VERSION_MAJOR}
        - phpughh/roadrunner/traefik:latest
    image: phpughh/roadrunner/traefik:${TRAEFIK_VERSION}

  ubuntu:
    build:
      context: build/ubuntu
      args:
        ubuntu_version: ${UBUNTU_VERSION_CODENAME}
      tags:
        - phpughh/roadrunner/ubuntu:${UBUNTU_VERSION}
        - phpughh/roadrunner/ubuntu:${UBUNTU_VERSION_CODENAME_NAME}
        - phpughh/roadrunner/ubuntu:latest
    image: phpughh/roadrunner/ubuntu:${UBUNTU_VERSION_CODENAME}

  zipkin:
    build:
      context: build/zipkin
      args:
        zipkin_version: ${ZIPKIN_VERSION}
      tags:
        - phpughh/roadrunner/zipkin:${ZIPKIN_VERSION_MAJOR}.${ZIPKIN_VERSION_MINOR}
        - phpughh/roadrunner/zipkin:${ZIPKIN_VERSION_MAJOR}
        - phpughh/roadrunner/zipkin:latest
    image: phpughh/roadrunner/zipkin:${ZIPKIN_VERSION}