networks:
  default:
    name: phpughh
    external: true

services:
  dev-cli:
    container_name: dev-cli
    hostname: dev-cli
    image: phpughh/roadrunner/php:${PHP_VERSION}-cli
    privileged: true
    tty: true
    stdin_open: true
    working_dir: /var/www
    volumes:
      - ../../:/var/www
    networks:
      - default

  mariadb:
    container_name: mariadb
    hostname: mariadb
    image: phpughh/roadrunner/mariadb:${MARIADB_VERSION}
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    ports:
      - target: 3306
        host_ip: 0.0.0.0
        published: "3306"
        protocol: tcp
        mode: host
    networks:
      - default

  nginx:
    depends_on:
      - php
    container_name: nginx
    hostname: nginx
    image: phpughh/roadrunner/nginx:${NGINX_VERSION}
    volumes:
      - ../:/var/www/webapp
#    ports:
#      - target: 80
#        host_ip: 0.0.0.0
#        published: "80"
#        protocol: tcp
#        mode: host
    networks:
      - default
    labels:
      - "traefik.enable=true"

      - "traefik.http.services.nginx-svc.loadbalancer.server.port=80"
      - "traefik.http.routers.nginx.entrypoints=http"
      - "traefik.http.routers.nginx.rule=HostRegexp(`{subdomain:.+}.phpug.hh`,`localhost`)"
      - "traefik.http.routers.nginx.priority=1"
      - "traefik.http.routers.nginx.service=nginx-svc"

  otel:
    container_name: otel-collector
    hostname: otel-collector
    command: [ "--config=/etc/otel-collector-config.yml" ]
    image: phpughh/roadrunner/otel-collector:${OTEL_COLLECTOR_VERSION}
    volumes:
      - ./res/otel-collector-config.yml:/etc/otel-collector-config.yml
#    ports:
#      - target: 4318
#        host_ip: 0.0.0.0
#        published: "4318"
#        protocol: tcp
#        mode: host
    networks:
      - default
    labels:
      - "traefik.enable=true"

      - "traefik.http.services.otel-svc.loadbalancer.server.port=4318"
      - "traefik.http.routers.otel.entrypoints=http"
      - "traefik.http.routers.otel.rule=Host(`otel-collector.phpug.hh`)"
      - "traefik.http.routers.otel.priority=2"
      - "traefik.http.routers.otel.service=otel-svc"

  traefik:
    container_name: traefik
    hostname: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--accesslog=true"
      - "--accesslog.filePath=/dev/stdout"
    image: phpughh/roadrunner/traefik:${TRAEFIK_VERSION}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - target: 80
        host_ip: 0.0.0.0
        published: "80"
        protocol: tcp
        mode: host
      - target: 443
        host_ip: 0.0.0.0
        published: "443"
        protocol: tcp
        mode: host
    networks:
      default:
        aliases:
          - otel-collector.phpug.hh
          - traefik.phpug.hh
          - www.phpug.hh
          - zipkin.phpug.hh
    privileged: true
    labels:
      - "traefik.enable=true"

      - "traefik.http.services.api-svc.loadbalancer.server.port=9999"

      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.phpug.hh`)"
      - "traefik.http.routers.traefik.priority=2"
      - "traefik.http.routers.traefik.service=api@internal"

  zipkin:
    container_name: zipkin
    hostname: zipkin
    image: phpughh/roadrunner/zipkin:${ZIPKIN_VERSION}
#    ports:
#      - target: 9411
#        host_ip: 0.0.0.0
#        published: "9411"
#        protocol: tcp
#        mode: host
    networks:
      - default
    labels:
      - "traefik.enable=true"

      - "traefik.http.services.zipkin-svc.loadbalancer.server.port=9411"
      - "traefik.http.routers.zipkin.entrypoints=http"
      - "traefik.http.routers.zipkin.rule=Host(`zipkin.phpug.hh`)"
      - "traefik.http.routers.zipkin.priority=2"
      - "traefik.http.routers.zipkin.service=zipkin-svc"