services:
  dev-cli:
    build:
      context: build/dev-cli
      args:
        codeception_version: ${CODECEPTION_VERSION}
        codeception_asserts_version: ${CODECEPTION_ASSERTS_VERSION}
        mariadb_root_password: ${MARIADB_ROOT_PASSWORD}
        php_version: ${PHP_VERSION}
    image: phpughh/roadrunner/php:${PHP_VERSION}-cli

  mariadb:
    build:
      context: build/mariadb
      args:
        mariadb_version: ${MARIADB_VERSION}
    image: phpughh/roadrunner/mariadb:${MARIADB_VERSION}

  nginx:
    build:
      context: build/nginx
      args:
        nginx_version: ${NGINX_VERSION}
    image: phpughh/roadrunner/nginx:${NGINX_VERSION}

  otel-collector:
    build:
      context: build/otel-collector
      args:
        otel_collector_version: ${OTEL_COLLECTOR_VERSION}
    image: phpughh/roadrunner/otel-collector:${OTEL_COLLECTOR_VERSION}

  php:
    build:
      context: build/php-fpm
      args:
        php_version: ${PHP_VERSION}
    image: phpughh/roadrunner/php:${PHP_VERSION}-fpm

  php-dev:
    build:
      context: build/php-fpm-dev
      args:
        php_version: ${PHP_VERSION}
    image: phpughh/roadrunner/php:${PHP_VERSION}-fpm-dev

  roadrunner:
    build:
      context: build/php-rr
      args:
        php_version: ${PHP_VERSION}
        roadrunner_version: ${ROADRUNNER_VERSION}
    image: phpughh/roadrunner/php:${PHP_VERSION}-rr

  roadrunner-dev:
    build:
      context: build/php-rr-dev
      args:
        php_version: ${PHP_VERSION}
    image: phpughh/roadrunner/php:${PHP_VERSION}-rr-dev

  zipkin:
    build:
      context: build/zipkin
      args:
        zipkin_version: ${ZIPKIN_VERSION}
    image: phpughh/roadrunner/zipkin:${ZIPKIN_VERSION}