include:
  - docker-compose.run.base.yml

services:
  php:
    depends_on:
      - mariadb
    container_name: php
    hostname: php
    image: phpughh/roadrunner/php:${PHP_VERSION}-rr-dev
    environment:
      - XDEBUG_HOST=${PHP_XDEBUG_HOST}
      - XDEBUG_PORT=${PHP_XDEBUG_PORT}
      - XDEBUG_CONNECT_ALWAYS=${PHP_XDEBUG_CONNECT_ALWAYS}
    volumes:
      - ../:/var/www/webapp
    labels:
      - "traefik.enable=true"

      - "traefik.http.services.rr-svc.loadbalancer.server.port=2112"
      - "traefik.http.routers.rr.entrypoints=http"
      - "traefik.http.routers.rr.rule=HostRegexp(`metrics.phpug.hh`)"
      - "traefik.http.routers.rr.priority=2"
      - "traefik.http.routers.rr.service=rr-svc"
