services:
  dev-cli:
    build:
      context: dev-cli
      args:
        codeception_version: ${CODECEPTION_VERSION}
        codeception_asserts_version: ${CODECEPTION_ASSERTS_VERSION}
        mariadb_root_password: ${MARIADB_ROOT_PASSWORD}
        php_version: ${PHP_VERSION}
    image: phpughh/roadrunner/php:${PHP_VERSION}-cli

  mariadb:
    build:
      context: mariadb
      args:
        mariadb_version: ${MARIADB_VERSION}
    image: phpughh/roadrunner/mariadb:${MARIADB_VERSION}

  nginx:
    build:
      context: nginx
      args:
        nginx_version: ${NGINX_VERSION}
    image: phpughh/roadrunner/nginx:${NGINX_VERSION}

  php:
    build:
      context: php-fpm
      args:
        php_version: ${PHP_VERSION}
    image: phpughh/roadrunner/php:${PHP_VERSION}-fpm

  php-dev:
    build:
      context: php-fpm-dev
      args:
        php_version: ${PHP_VERSION}
    image: phpughh/roadrunner/php:${PHP_VERSION}-fpm-dev

  roadrunner:
    build:
      context: php-rr
      args:
        php_version: ${PHP_VERSION}
        roadrunner_version: ${ROADRUNNER_VERSION}
    image: phpughh/roadrunner/php:${PHP_VERSION}-rr

  roadrunner-dev:
    build:
      context: php-rr-dev
      args:
        php_version: ${PHP_VERSION}
    image: phpughh/roadrunner/php:${PHP_VERSION}-rr-dev